name: client-app           # Nombre único de tu aplicación
version: '1.0.0'           # Versión de tu aplicación
summary: Aplicación Cliente # Breve descripción
description: |
  Cliente, un programa en C con múltiples dependencias empaquetado como Snap.

base: core20               # Base para Ubuntu 20.04
confinement: strict        # Seguridad estricta
grade: stable              # Para versiones finales (o usa 'devel' para pruebas)

apps:
  client:
    command: Client
    plugs: [network, home] # Permisos necesarios, como acceso a red o carpetas de usuario

parts:
  client:
    plugin: cmake          # Construcción usando CMake
    source: .              # Carpeta raíz del proyecto
    build-packages:        # Paquetes necesarios para la compilación
      - build-essential
      - cmake
      - python3
      - python3-venv
      - python3-pip
      - curl
    override-build: |
      # Crear un entorno virtual para Conan
      python3 -m venv venv
      source venv/bin/activate
      
      # Instalar Conan en el venv
      pip install --upgrade pip
      pip install conan

      # Copiar los archivos de Conan al directorio de construcción
      cp ${SNAPCRAFT_PROJECT_DIR}/conanfile.py .
      cp ${SNAPCRAFT_PROJECT_DIR}/conandata.yml .

      # Instalar dependencias usando Conan
      conan install . --build=missing
      
      # Continuar con la compilación
      snapcraftctl build
    stage-packages:        # Paquetes necesarios en el runtime
      - libc6
      - python3
      - python3-minimal
